// <auto-generated />
using ConsoleApp2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp2.Migrations
{
    [DbContext(typeof(MusicDbContext))]
    [Migration("20230819131705_Filling")]
    partial class Filling
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ConsoleApp2.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("GenreId")
                        .IsUnique();

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 1,
                            GenreId = 1,
                            Name = "Yupe",
                            Year = 1987
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 2,
                            GenreId = 2,
                            Name = "Jane",
                            Year = 2001
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 3,
                            GenreId = 3,
                            Name = "Lux",
                            Year = 1774
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 4,
                            GenreId = 4,
                            Name = "Wex",
                            Year = 988
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 5,
                            GenreId = 5,
                            Name = "Kvas",
                            Year = 123
                        },
                        new
                        {
                            Id = 6,
                            ArtistId = 6,
                            GenreId = 6,
                            Name = "Octarine",
                            Year = 1001
                        },
                        new
                        {
                            Id = 7,
                            ArtistId = 7,
                            GenreId = 7,
                            Name = "Spell Prism",
                            Year = 1111
                        },
                        new
                        {
                            Id = 8,
                            ArtistId = 8,
                            GenreId = 8,
                            Name = "Black Hole",
                            Year = 2223
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Uzi"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 2,
                            Name = "Chieff Kiff"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 3,
                            Name = "Bobby Shmurda"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 4,
                            Name = "Vert"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 5,
                            Name = "Goblin"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 6,
                            Name = "Justaf"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 7,
                            Name = "Drive"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 8,
                            Name = "Juggernut"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "For Child"
                        },
                        new
                        {
                            Id = 2,
                            Name = "For Adult"
                        },
                        new
                        {
                            Id = 3,
                            Name = "For Grandparents"
                        },
                        new
                        {
                            Id = 4,
                            Name = "For Teenager"
                        },
                        new
                        {
                            Id = 5,
                            Name = "For Family"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "United States of America"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Japan"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Jazz"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chill"
                        },
                        new
                        {
                            Id = 3,
                            Name = ""
                        },
                        new
                        {
                            Id = 4,
                            Name = "Vibe"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Metal"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Hard Rock"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 8,
                            Name = "EDM"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.PlayList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SongId");

                    b.ToTable("PlayLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            SongId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            SongId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            SongId = 3
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            SongId = 4
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            SongId = 5
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 1,
                            Duration = "12:44"
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 2,
                            Duration = "60:71"
                        },
                        new
                        {
                            Id = 3,
                            AlbumId = 3,
                            Duration = "24:33"
                        },
                        new
                        {
                            Id = 4,
                            AlbumId = 4,
                            Duration = "1:23"
                        },
                        new
                        {
                            Id = 5,
                            AlbumId = 5,
                            Duration = "12:65"
                        },
                        new
                        {
                            Id = 6,
                            AlbumId = 6,
                            Duration = "43:77"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Album", b =>
                {
                    b.HasOne("ConsoleApp2.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp2.Genre", "Genre")
                        .WithOne("Album")
                        .HasForeignKey("ConsoleApp2.Album", "GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("ConsoleApp2.Artist", b =>
                {
                    b.HasOne("ConsoleApp2.Country", "Country")
                        .WithMany("Artists")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ConsoleApp2.PlayList", b =>
                {
                    b.HasOne("ConsoleApp2.Category", "Category")
                        .WithMany("PlayLists")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp2.Song", "Song")
                        .WithMany("PlayLists")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("ConsoleApp2.Song", b =>
                {
                    b.HasOne("ConsoleApp2.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("ConsoleApp2.Category", b =>
                {
                    b.Navigation("PlayLists");
                });

            modelBuilder.Entity("ConsoleApp2.Country", b =>
                {
                    b.Navigation("Artists");
                });

            modelBuilder.Entity("ConsoleApp2.Genre", b =>
                {
                    b.Navigation("Album")
                        .IsRequired();
                });

            modelBuilder.Entity("ConsoleApp2.Song", b =>
                {
                    b.Navigation("PlayLists");
                });
#pragma warning restore 612, 618
        }
    }
}
